smtp_password: '2Mf,IAp!'
smtp_on: true
smtp_autotls: true
smtp_host: smtp.gmail.com
smtp_hostbackup: ''
smtp_port: '465'
smtp_protocol: ssl
smtp_timeout: 1
smtp_username: hiya.patel@innoraft.com
smtp_from: hiya.patel@innoraft.com
smtp_fromname: Hiya
smtp_client_hostname: ''
smtp_client_helo: ''
smtp_allowhtml: '0'
smtp_debugging: false
smtp_keepalive: true
