interface:
<<<<<<< HEAD
  default: SMTPMailSystem
=======
  default: php_mail
>>>>>>> cec6bb9255f4dd59c3b7f5b10dcc1dbe919ae800
_core:
  default_config_hash: rYgt7uhPafP2ngaN_ZUPFuyI4KdE0zU868zLNSlzKoE
